resolver: lts-18.3

packages:
    - 'bioinformatics-toolkit'
    - 'bioinformatics-toolkit-apps'

extra-deps:
    - clustering-0.4.1
    - HsHTSLib-1.9.2

flags:
  cryptonite:
    use_target_attributes: false
